### ISSUE TITLE
Could you please provide the SemEval2010-Task 8 in json format?

### ISSUE THREAD

**Issue by vhientran** [zzysay/KD4NRE#4]
Hi @zzysay ,
Thank you for releasing the source code of your paper (AAAI 2020) on TACRED dataset. If possible, could you please provide the preprocessed SemEval2010-Task 8 in json format? Also, I am grateful if you can release the source code on this dataset. Thank you for your consideration!

**Comment by zzysay** [comment]
Hi @hientrannaist, sorry for the late reply and thanks for your interest.

Please find the preprocessed SemEval data that we used in this google drive folder: [https://drive.google.com/open?id=1ir-DLqnW2BFA5Swt2plVXzVmCye-QyWA](https://drive.google.com/open?id=1ir-DLqnW2BFA5Swt2plVXzVmCye-QyWA) (which is obtained from the author of C-GCN). 
As runnable code, the implementation of AG-GCN may be useful for you: [https://github.com/Cartus/AGGCN/tree/master/semeval](https://github.com/Cartus/AGGCN/tree/master/semeval), and you can replace the base encoder with it.
